# Generated by Django 2.0.2 on 2018-03-05 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author', models.CharField(max_length=250)),
                ('Publisher', models.CharField(max_length=250)),
                ('Type', models.CharField(max_length=100)),
                ('Book_logo', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Book_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=100)),
                ('file_title', models.CharField(max_length=250)),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Book')),
            ],
        ),
    ]
