# Generated by Django 2.0.2 on 2018-03-08 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_year', models.CharField(max_length=100)),
                ('file_type', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='book_name',
            name='Book',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Type',
            new_name='Typegenre',
        ),
        migrations.DeleteModel(
            name='Book_name',
        ),
        migrations.AddField(
            model_name='book_format',
            name='Book_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Book'),
        ),
    ]
